In [1]:
import pandas as pd

In [2]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../scripts')))

In [3]:
from RFMSScore import *
from plottings import *

In [4]:
df = pd.read_csv('../data/processed_data.csv')

In [5]:
df.head()

,index,CustomerId,Amount,TransactionStartTime,PricingStrategy,FraudResult,TotalTransactionAmount,AverageTransactionAmount,TotalTransactions,StdTransactionAmount,...,ProductCategory_movies,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill,ChannelId_ChannelId_1,ChannelId_ChannelId_2,ChannelId_ChannelId_3,ChannelId_ChannelId_5
0,0,CustomerId_4406,1000.0,2018-11-15 02:18:49+00:00,2,0,0.557522,0.047184,-0.311831,-0.167524,...,0,0,0,0,0,0,0,0,1,0
1,1,CustomerId_4406,-20.0,2018-11-15 02:19:08+00:00,2,0,0.557522,0.047184,-0.311831,-0.167524,...,0,0,0,0,0,0,0,1,0,0
2,2,CustomerId_4683,500.0,2018-11-15 02:44:21+00:00,2,0,0.556944,0.047137,-0.444993,-0.201719,...,0,0,0,0,0,0,0,0,1,0
3,3,CustomerId_988,20000.0,2018-11-15 03:32:55+00:00,2,0,0.558153,0.047749,-0.404020,-0.008737,...,0,0,0,0,0,1,0,0,1,0
4,4,CustomerId_988,-644.0,2018-11-15 03:34:21+00:00,2,0,0.558153,0.047749,-0.404020,-0.008737,...,0,0,0,0,0,0,0,1,0,0

In [12]:
df.columns

Index(['index', 'CustomerId', 'Amount', 'TransactionStartTime',
       'PricingStrategy', 'FraudResult', 'TotalTransactionAmount',
       'AverageTransactionAmount', 'TotalTransactions', 'StdTransactionAmount',
       'TransactionHour', 'TransactionDay', 'TransactionMonth',
       'TransactionYear', 'ProductCategory_airtime',
       'ProductCategory_data_bundles', 'ProductCategory_financial_services',
       'ProductCategory_movies', 'ProductCategory_other',
       'ProductCategory_ticket', 'ProductCategory_transport',
       'ProductCategory_tv', 'ProductCategory_utility_bill',
       'ChannelId_ChannelId_1', 'ChannelId_ChannelId_2',
       'ChannelId_ChannelId_3', 'ChannelId_ChannelId_5', 'Recency'],
      dtype='object')

In [10]:
RFMS = RFMSCalculator(df)

In [11]:
df_rfms = RFMS.calculate_rfms()

KeyError: "Column(s) ['TransactionId'] do not exist"